repoURL: 'https://github.com/iamchoiz/k8-cicd-argocd.git'
apps:
  - name: kustomize-app
    project: default
    namespace: default
    source:
      path: kustomize_app
      # customValues: true
      # values:
      #   - values-eks.yaml
  # - name: prometheus
  #   project: default
  #   namespace: prom
  #   source:
  #     path: prometheus
  #     customValues: true
  #     values:
  #       - values-eks.yaml
  # - name: grafana
  #   project: default
  #   namespace: grafana
  #   source:
  #     path: grafana
  #     customValues: true
  #     values:
  #       - values-eks.yaml
  # - name: fluentbit
  #   project: default
  #   namespace: fluentbit
  #   source:
  #     path: fluent-bit
  #     customValues: true
  #     values:
  #       - values-eks.yaml
  # - name: aws-cli-batch
  #   project: default
  #   namespace: default
  #   source:
  #     path: aws-cli
  #     customValues: true
  #     values:
  #       - values-eks.yaml