apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: default
    server: 'https://kubernetes.default.svc'
  project: dev
  source:
    repoURL: https://github.com/iamchoiz/k8-cicd-argocd.git
    targetRevision: HEAD
    path: app-of-apps
    helm:
      valueFiles:
        - values-local.yaml
  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true
#      allowEmpty: false
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=background
