replicas: 1
image:
  repository: 454865828152.dkr.ecr.ap-northeast-2.amazonaws.com/demo
  tag: 2.0.0
  imagePullSecrets:
    - name: ecr-cred
service:
  type: NodePort
  protocol: TCP
  targetPort: 80
  port: 80
  nodePort: 30000
ingress:
  enabled: false
