apiVersion: v1
kind: Secret
metadata:
  name: another-secret
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
data:
  clientSecret: Mzk1Njg1YWFlYjIxMGRkOWY3NDk3MDNiMWViOGVlZjk2ZTdjNWU5Zg==
